apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    github.com/workflows: app-ci.yml
    backstage.io/techdocs-ref: dir:.
  tags:
    - dotnet
    - aspnet
    - webapi
    - ${{ values.deploymentTarget }}
    - gcp
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.name }}-system
